config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "artists#index"

  resources :artists do
    resources :songs
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/artist.rb
class Artist < ApplicationRecord
  has_many :songs, dependent: :destroy
  has_one :photo, dependent: :destroy

  @desc = false

  validates :name, presence: true
  validates :age, numericality: { only_integer: true, :greater_than_or_equal_to => 3 }, presence: true
  validates :bio, presence: true, length: { maximum: 500 }



  def self.descender
     @desc = true
  end

  def self.descenderOff
     @desc = false
  end

  def self.descenderValue
    @desc

  end

end

app/models/photo.rb
class Photo < ApplicationRecord
  belongs_to :artist

  mount_uploader :image, ImageUploader
end

app/models/song.rb
class Song < ApplicationRecord
  belongs_to :artist

  validates :name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/artists_controller.rb
class ArtistsController < ApplicationController

    def index
        respond_to do |format|
          @artists=Artist.all.order(:name)
          format.html{}
          format.json{render status: 200, json: @artists}
        end
     end

     def show
       respond_to do |format|
         @artist = Artist.find(params[:id])
         format.html{ @songs = @artist.songs }
        format.json{render status: 200, json: @artist}
       end
     end



     def destroy
       artist=Artist.find(params[:id])
       artist.destroy
       redirect_to root_path

    #    render status: 200, json: {
    #   message: "Artist successfully deleted"
    # }.to_json

     end





end

app/controllers/songs_controller.rb
class SongsController < ApplicationController
  before_action :set_artist

  def create
    song_params = params.require(:song).permit(:name)
    @song=@artist.songs.create(song_params)

    if @song.save!
      respond_to do |format|
        format.html{redirect_to artist_path(@artist.id)}
        format.json { render json: @song }
      end
    else
      respond_to do |format|
        format.html { redirect_to artist_path }
        format.json { render json: @song.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    song=Song.find(params[:id])
    song.destroy

    respond_to do |format|
      format.json{ render status: 200, json: {} }
      format.html{ redirect_to artist_path(@artist.id) }
   end
  end

  private

  def set_artist
    @artist = Artist.find(params[:artist_id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/artists_helper.rb
module ArtistsHelper
end

app/helpers/songs_helper.rb
module SongsHelper
end

app/views/artists/index.html.erb
<h1>Artists</h1>

<% @artists.each do |artist| %>

  <p><%= image_tag artist.photo.image %><%= link_to artist.name, artist_path(artist.id) %></p>

<% end %>

app/views/artists/show.html.erb
<h1><%= @artist.name %></h1>

<p>Age: <%= @artist.age %></p>
<p>Biography: <%= @artist.bio %></p>

<ul id="songlist">
<p>Songs: <% @artist.songs.each do |song| %></p>

<li class="song" id="<%= song.id %>">
  <% ar = @artist.id.to_s %>
  <% sg = song.id.to_s %>
  <%= song.name %>
<button class="btndelete" id="<%=song.name%>" onclick="<%="deleteSong(#{ar},#{sg})" %>">Delete Song</button></li>

<p><% end %></p>
</ul>
<p><%= image_tag @artist.photo.image %></p>

<%= link_to "Delete Artist", artist_path(@artist.id), method: :delete, data: { confirm: "Are you sure?" } %>


<button onclick="<%="deleteAllSongs()"%>">Delete All Songs</button>

<h1>New song</h1>

<%= render 'songs/form' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Codaisseurify</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>

    <div class="container">
      <%= yield %>
    </div>

  </body>
</html>

app/views/songs/_form.html.erb
<%= form_for [@artist,@artist.songs.new], remote: true, url: artist_songs_path(@artist.id), method: :create do |a| %>
  <%= a.label :name %>
  <%= a.text_field :name %>

  <%= a.submit "Create" %>
<% end %>